worker_processes auto;

events {
    worker_connections 768;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    upstream performance {
        server performance:80;
    }

    upstream social {
        server social:80;
    }

    server {
        listen 80;
        server_name localhost;

        # 🚀 Redirigir la raíz "/" a index.html sin usar "/index"
        location = / {
            proxy_pass http://performance;
            # rewrite ^/performance/?$ /index.html break;
        }

        # 🚀 Redirigir "/social" al contenedor "social"
        location /social {
            proxy_pass http://social;
            rewrite ^/social/?$ /index.html break;
        }
        

        error_page 404 /404.html;
        location = /404.html {
            root /usr/share/nginx/html;
        }
    }
}
